#!/bin/sh

# Exit script in case of error
set -e

printf "\n\nCreating autogenerated certificates for LAN host"
mkdir -p "/spcgeonode-certificates/autoissued/"
openssl req -x509 -nodes -days 1825 -newkey rsa:2048 -keyout "/spcgeonode-certificates/autoissued/privkey.pem" -out "/spcgeonode-certificates/autoissued/fullchain.pem" -subj "/CN=$LAN_HOST" 

printf "\n\nCreating symbolic link for WAN host"
ln -sf "/spcgeonode-certificates/autoissued/" "/certificate_symlink"

printf "\n\nReplacing environement variables"
envsubst '\$LAN_HOST \$WAN_HOST \$RESOLVER' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf

printf "\n\nLoading nginx autoreloader\n"
sh /docker-autoreload.sh &

# Run the CMD 
exec "$@"
