#!/bin/sh

# Exit script in case of error
set -e

printf "\n\nCreating autogenerated certificates for LAN host"
mkdir -p "/spcgeonode-certificates/autoissued/"
openssl req -x509 -nodes -days 1825 -newkey rsa:2048 -keyout "/spcgeonode-certificates/autoissued/privkey.pem" -out "/spcgeonode-certificates/autoissued/fullchain.pem" -subj "/CN=$HTTP_HOST" 

echo "Creating symbolic link for WAN host"
# for some reason, the ln -f flag doesn't work below...
rm -f /certificate_symlink
if [ -f "/spcgeonode-certificates/$LETSENCRYPT_MODE/live/$HTTPS_HOST/fullchain.pem" ] && [ -f "/spcgeonode-certificates/$LETSENCRYPT_MODE/live/$HTTPS_HOST/privkey.pem" ]; then
        echo "Certbot certificate exists, we symlink to the live cert"
        ln -sf "/spcgeonode-certificates/$LETSENCRYPT_MODE/live/$HTTPS_HOST" /certificate_symlink
else
        echo "Certbot certificate does not exist, we symlink to autoissued"
        ln -sf "/spcgeonode-certificates/autoissued" /certificate_symlink
fi

printf "\n\nReplacing environement variables"
envsubst '\$HTTP_HOST \$HTTPS_HOST \$RESOLVER' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf

printf "\n\nLoading nginx autoreloader\n"
sh /docker-autoreload.sh &

# Run the CMD 
exec "$@"
