#!/bin/sh

# Exit script in case of error
set -e

echo '--- START Geoserver Docker Entrypoint ---'

# TODO : see if we can have startup.sh exit on error
# (eg. when starting before django migrations, the user tables are missing)

# Run migrations
echo 'Initializing data dir'
if [ -f /spcgeonode-geodatadir/spcgeonode_init_flag ]; then
    echo 'Geodatadir already initialized, skipping initialization...'
else
    echo 'Geodatadir empty, we run initialization...'
    cp -Rf /geodatadir-overrides/. /spcgeonode-geodatadir/
fi

echo 'Resetting master password '
if [ ! -f /spcgeonode-geodatadir/security/spcgeonode_masterpwd_needs_reset_flag ]; then
    echo 'Master password already reset, skipping password reset...'
else
    echo 'Master password not modified, we reset it...'

    OLD_PASSWORD="8ehebOTQ5qyts8XlgTcS9ZjQolWFLgk3"
    NEW_PASSWORD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

    echo "Updating the keystore main password"
    keytool -storepasswd -new "$NEW_PASSWORD" -keystore /spcgeonode-geodatadir/security/geoserver.jceks -storetype JCEKS -storepass "$OLD_PASSWORD"

    echo "Updating the digest"
    (printf "digest1:" && /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -classpath /geoserver-2.12.2/webapps/geoserver/WEB-INF/lib/jasypt-1.8.jar org.jasypt.intf.cli.JasyptStringDigestCLI digest.sh algorithm=SHA-256 saltSizeBytes=16 iterations=100000 input="$NEW_PASSWORD" verbose=0) | tr -d '\n' > /spcgeonode-geodatadir/security/masterpw.digest

    echo "Saving the encrypted password"    
    # The key (5lp6...) is generated by this strange code here, which is hardcoded.:  https://github.com/geoserver/geoserver/blob/e4817074ef05fe96f446e8f3ca7449c6c4f95b65/src/main/src/main/java/org/geoserver/security/password/URLMasterPasswordProvider.java
    /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -classpath /geoserver-2.12.2/webapps/geoserver/WEB-INF/lib/jasypt-1.8.jar org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI input="$NEW_PASSWORD" password='5lp6`U#!rxUuH%nILQqnr3XQPnJd5X$lUFT)cXUU' verbose=0 | tr -d '\n' > /spcgeonode-geodatadir/security/masterpw/default/passwd

    echo "Unsetting env vars"
    OLD_PASSWORD=""
    NEW_PASSWORD=""

    echo "Removing obsolete masterpw.info"
    rm /spcgeonode-geodatadir/security/masterpw.info

    # DO NOT USE THIS ! is stores the password in plain text in datadir
    # users can recover the master password anyway from the UI
    # echo "Saving masterpw.info" 
    # echo "The root password is not $NEW_PASSWORD" > /spcgeonode-geodatadir/security/masterpw.info

    echo "Removing password needs reset flag"
    rm /spcgeonode-geodatadir/security/spcgeonode_masterpwd_needs_reset_flag
fi
 
echo "Waiting for geonode to be initialized"
until psql -h postgres -U postgres -d postgres -c 'SELECT 1 FROM public.groups_groupprofile LIMIT 1;' > /dev/null; do
  echo "Postgres unavailable or groups_groupprofile table does not exist."
  echo "Make sure Postgres is started and Geonode finished initalization."
  echo "Retrying in 10 seconds"
  sleep 10
done

 
echo '--- END Geoserver Docker Entrypoint ---'

# Run the CMD 
exec "$@"
