FROM alpine:3.7

# TODO : IMPLEMENT

# This doesn't do anything yet. It should launch a service to backup to some cloud somewhere... (resilio, dropbox, amazon, or whatever ?)

CMD ["sleep", "3600s"]